Subsample example data to 50 sequences
nextstrain/monkeypox pull request #78
Opened 2022-06-22 17:20 UTC by victorlin

### Description of proposed changes

Metadata and sequences files are sourced from elsewhere now (see d5bf10829e95552d59c332bc6c2f11dd8aa2c0f5 + a7f3d272b8008729ad215de6fec1dc11f48f423b).
The example_data/ files are still used by CI, but a smaller set of data is sufficient and allows for faster CI runs.

Method:

```sh
cd example_data/
augur filter \
    --metadata metadata.tsv \
    --metadata-id-columns accession \
    --sequences sequences.fasta \
    --subsample-max-sequences 50 \
    --output-metadata metadata2.tsv \
    --output-sequences sequences2.fasta
mv metadata2.tsv metadata.tsv
mv sequences2.fasta sequences.fasta
```

Output:

```
Note: You did not provide a sequence index, so Augur will generate one. You can generate your own index ahead of time with `augur index` and pass it with `augur filter --sequence-index`.
364 strains were dropped during filtering
	234 had no metadata
	3 had no sequence data
	127 of these were dropped because of subsampling criteria
50 strains passed all filters
```

### Related issue(s)

- Motivation: https://github.com/nextstrain/monkeypox/pull/62#issuecomment-1158047607

### Testing

See checks.

2022-06-22 17:54 UTC, trvrb commented
Thanks for attending to this @victorlin. However, the metadata downloaded from data.nextstrain.org has had its fields updated recently. Can you regenerate the 50 sequence example data from a fresh download? Also, can you ensure that the 50 genomes include all clades under the field `clade` and all all lineages under the field `lineage`?

2022-06-22 17:55 UTC, trvrb requested changes
Thanks for attending to this @victorlin. However, the metadata downloaded from data.nextstrain.org has had its fields updated recently. Can you regenerate the 50 sequence example data from a fresh download? Also, can you ensure that the 50 genomes include all clades under the field `clade` and all all lineages under the field `lineage`?

2022-06-22 19:27 UTC, victorlin commented
@trvrb done, 3 notable changes:

1. Sourced from data.nextstrain.org
2. Used `--group-by clade lineage` to ensure all clades and all lineages are accounted for
3. Used `--include-where strain=MK783032 strain=MK783030` to ensure the root (defined in config_hmpxv1.yaml) is included

2022-06-28 07:24 UTC, rneher approved these changes

2022-06-28 16:35 UTC, merged